import React, { useState, useEffect, useContext } from 'react';
import { Plus, Search, Edit2, Trash2, UserCheck, UserX, Save, X, GraduationCap, Upload, Download, FileSpreadsheet, ArrowLeft, ChevronLeft, ChevronRight } from 'lucide-react';
import { ThemeContext } from '../App';

export default function ManajemenDosen({ dosenViewMode, setDosenViewMode }) {
  const { isDarkMode } = useContext(ThemeContext);
  const [dosenList, setDosenList] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterActive, setFilterActive] = useState('all'); // 'all', 'active', 'inactive'
  const [filterProdi, setFilterProdi] = useState('all'); // Filter prodi
  const [filterPeriode, setFilterPeriode] = useState('all'); // Filter periode
  const [periodeList, setPeriodeList] = useState([]); // List of available periodes
  
  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(25);
  
  // Form state for add/edit
  const [selectedDosen, setSelectedDosen] = useState(null);
  const [formData, setFormData] = useState({
    id_dosen: '',
    nip: '',
    nama: '',
    prodi: '',
    email: '',
    no_telepon: '',
    id_periode: null,
    is_active: 1
  });
  
  // Import modal state
  const [showImportModal, setShowImportModal] = useState(false);
  const [importFile, setImportFile] = useState(null);
  const [isImporting, setIsImporting] = useState(false);
  const [importResult, setImportResult] = useState(null);

  useEffect(() => {
    fetchDosen();
    fetchPeriodeList();
  }, []);

  const fetchDosen = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('http://localhost:4000/api/dosen');
      if (response.ok) {
        const data = await response.json();
        setDosenList(data);
      }
    } catch (err) {
      console.error('Error fetching dosen:', err);
      alert('Gagal memuat data dosen');
    } finally {
      setIsLoading(false);
    }
  };

  const fetchPeriodeList = async () => {
    try {
      const response = await fetch('http://localhost:4000/api/periode');
      if (response.ok) {
        const data = await response.json();
        setPeriodeList(data);
      }
    } catch (err) {
      console.error('Error fetching periode:', err);
    }
  };

  const handleAdd = () => {
    setSelectedDosen(null);
    setFormData({
      id_dosen: '',
      nip: '',
      nama: '',
      prodi: '',
      email: '',
      no_telepon: '',
      id_periode: periodeList.find(p => p.is_active)?.id_periode || null,
      is_active: 1
    });
    setDosenViewMode('add');
  };

  const handleEdit = (dosen) => {
    setSelectedDosen(dosen);
    setFormData({
      id_dosen: dosen.id_dosen,
      nip: dosen.nip,
      nama: dosen.nama,
      prodi: dosen.prodi || '',
      email: dosen.email || '',
      no_telepon: dosen.no_telepon || '',
      id_periode: dosen.id_periode || null,
      is_active: dosen.is_active
    });
    setDosenViewMode('edit');
  };

  const handleCancel = () => {
    setDosenViewMode('list');
    setSelectedDosen(null);
    setFormData({
      id_dosen: '',
      nip: '',
      nama: '',
      prodi: '',
      email: '',
      no_telepon: '',
      id_periode: null,
      is_active: 1
    });
  };

  const handleSave = async () => {
    if (!formData.nip || !formData.nama) {
      alert('NIP dan Nama wajib diisi!');
      return;
    }

    if (!formData.id_periode) {
      alert('Periode wajib dipilih!');
      return;
    }

    try {
      const url = selectedDosen 
        ? `http://localhost:4000/api/dosen/${selectedDosen.id_dosen}`
        : 'http://localhost:4000/api/dosen';
      
      // Don't send id_dosen when creating new dosen (will be auto-generated by backend)
      const payload = selectedDosen 
        ? formData 
        : { nip: formData.nip, nama: formData.nama, prodi: formData.prodi, email: formData.email, no_telepon: formData.no_telepon, id_periode: formData.id_periode, is_active: formData.is_active };
      
      const response = await fetch(url, {
        method: selectedDosen ? 'PUT' : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        alert(selectedDosen ? 'Dosen berhasil diupdate!' : 'Dosen berhasil ditambahkan!');
        setDosenViewMode('list');
        fetchDosen();
      } else {
        const error = await response.json();
        alert('Gagal menyimpan: ' + error.error);
      }
    } catch (err) {
      alert('Error: ' + err.message);
    }
  };

  const handleDelete = async (id, nama) => {
    if (!window.confirm(`Yakin ingin menghapus dosen "${nama}"? Data akan dihapus permanen dari database.`)) return;

    try {
      const response = await fetch(`http://localhost:4000/api/dosen/${id}`, {
        method: 'DELETE'
      });

      if (response.ok) {
        alert('Dosen berhasil dihapus');
        fetchDosen();
      } else {
        const error = await response.json();
        alert('Gagal menghapus: ' + error.error);
      }
    } catch (err) {
      alert('Error: ' + err.message);
    }
  };

  const handleToggleActive = async (id, currentStatus, nama) => {
    const newStatus = currentStatus ? 0 : 1;
    const action = newStatus ? 'mengaktifkan' : 'menonaktifkan';
    
    if (!window.confirm(`Yakin ingin ${action} dosen "${nama}"?`)) return;

    try {
      const response = await fetch(`http://localhost:4000/api/dosen/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...dosenList.find(d => d.id_dosen === id), is_active: newStatus })
      });

      if (response.ok) {
        alert(`Dosen berhasil ${newStatus ? 'diaktifkan' : 'dinonaktifkan'}`);
        fetchDosen();
      }
    } catch (err) {
      alert('Error: ' + err.message);
    }
  };
  
  const handleImportFile = async () => {
    if (!importFile) {
      alert('Pilih file Excel terlebih dahulu!');
      return;
    }
    
    setIsImporting(true);
    setImportResult(null);
    
    try {
      const formData = new FormData();
      formData.append('file', importFile);
      
      const response = await fetch('http://localhost:4000/api/dosen/import', {
        method: 'POST',
        body: formData
      });
      
      // Check if response is JSON
      const contentType = response.headers.get('content-type');
      if (!contentType || !contentType.includes('application/json')) {
        throw new Error('Server mengembalikan response bukan JSON. Kemungkinan ada error. Cek console backend.');
      }
      
      const result = await response.json();
      
      if (response.ok) {
        setImportResult({
          success: true,
          message: result.message,
          total: result.total,
          success_count: result.success_count,
          failed_count: result.failed_count,
          errors: result.errors || []
        });
        fetchDosen(); // Refresh list
      } else {
        setImportResult({
          success: false,
          message: result.error || 'Import gagal'
        });
      }
    } catch (err) {
      console.error('Import error:', err);
      setImportResult({
        success: false,
        message: 'Error: ' + err.message
      });
    } finally {
      setIsImporting(false);
    }
  };
  
  // Get unique prodi list
  const prodiList = [...new Set(dosenList.map(d => d.prodi).filter(Boolean))];

  // Filter and search
  const filteredDosen = dosenList.filter(dosen => {
    const matchSearch = 
      (dosen.id_dosen && dosen.id_dosen.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (dosen.nama && dosen.nama.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (dosen.nip && dosen.nip.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (dosen.prodi && dosen.prodi.toLowerCase().includes(searchQuery.toLowerCase()));
    
    const matchFilter = 
      filterActive === 'all' ? true :
      filterActive === 'active' ? dosen.is_active === 1 :
      dosen.is_active === 0;
    
    const matchProdi = 
      filterProdi === 'all' ? true :
      dosen.prodi === filterProdi;
    
    const matchPeriode = 
      filterPeriode === 'all' ? true :
      dosen.id_periode === parseInt(filterPeriode);
    
    return matchSearch && matchFilter && matchProdi && matchPeriode;
  });

  // Pagination
  const totalPages = Math.ceil(filteredDosen.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const paginatedDosen = filteredDosen.slice(startIndex, endIndex);

  // Reset to page 1 when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, filterActive, filterProdi, filterPeriode, itemsPerPage]);

  const handlePageChange = (page) => {
    setCurrentPage(page);
  };

  const handleItemsPerPageChange = (value) => {
    setItemsPerPage(value);
    setCurrentPage(1);
  };

  return (
    <section className="space-y-6">
      {/* ADD/EDIT FORM VIEW */}
      {(dosenViewMode === 'add' || dosenViewMode === 'edit') && (
        <>
          {/* Back Button */}
          <button
            onClick={handleCancel}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
              isDarkMode 
                ? 'bg-gray-700 hover:bg-gray-600 text-white border border-gray-600' 
                : 'bg-white hover:bg-gray-50 text-gray-700 border border-gray-300'
            }`}
          >
            <ArrowLeft size={16} />
            Kembali
          </button>

          {/* Form Card */}
          <div className={`glass-card ${isDarkMode ? 'bg-gray-800/60 border-gray-700' : 'bg-white/90 border-gray-200'} p-6`}>
            <h4 className={`text-xl font-bold mb-5 ${isDarkMode ? 'text-white' : 'text-gray-800'}`}>
              {dosenViewMode === 'edit' ? 'Edit Data Dosen' : 'Tambah Dosen Baru'}
            </h4>

            <div className="space-y-4">
              <div>
                <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  NIP <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={formData.nip}
                  onChange={(e) => setFormData({ ...formData, nip: e.target.value })}
                  placeholder="19800101"
                  className={`w-full px-3 py-2 border rounded-lg ${
                    isDarkMode 
                      ? 'bg-gray-700 border-gray-600 text-white' 
                      : 'bg-white border-gray-300 text-gray-800'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                />
              </div>

              <div>
                <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Nama Lengkap <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={formData.nama}
                  onChange={(e) => setFormData({ ...formData, nama: e.target.value })}
                  placeholder="Ahmad Fauzi"
                  className={`w-full px-3 py-2 border rounded-lg ${
                    isDarkMode 
                      ? 'bg-gray-700 border-gray-600 text-white' 
                      : 'bg-white border-gray-300 text-gray-800'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                />
              </div>

              <div>
                <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Program Studi
                </label>
                <input
                  type="text"
                  value={formData.prodi}
                  onChange={(e) => setFormData({ ...formData, prodi: e.target.value })}
                  placeholder="Informatika"
                  className={`w-full px-3 py-2 border rounded-lg ${
                    isDarkMode 
                      ? 'bg-gray-700 border-gray-600 text-white' 
                      : 'bg-white border-gray-300 text-gray-800'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                />
              </div>

              <div>
                <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Periode KKN <span className="text-red-500">*</span>
                </label>
                <select
                  value={formData.id_periode || ''}
                  onChange={(e) => setFormData({ ...formData, id_periode: e.target.value ? parseInt(e.target.value) : null })}
                  className={`w-full px-3 py-2 border rounded-lg ${
                    isDarkMode 
                      ? 'bg-gray-700 border-gray-600 text-white' 
                      : 'bg-white border-gray-300 text-gray-800'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                >
                  <option value="">-- Pilih Periode --</option>
                  {periodeList.map(periode => (
                    <option key={periode.id_periode} value={periode.id_periode}>
                      {periode.nama_periode} {periode.is_active ? '✓' : ''}
                    </option>
                  ))}
                </select>
                <p className={`text-xs mt-1 ${isDarkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                  Pilih periode KKN untuk dosen ini
                </p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                    Email
                  </label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    placeholder="email@universitas.ac.id"
                    className={`w-full px-3 py-2 border rounded-lg ${
                      isDarkMode 
                        ? 'bg-gray-700 border-gray-600 text-white' 
                        : 'bg-white border-gray-300 text-gray-800'
                    } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                  />
                </div>
                <div>
                  <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                    No. Telepon
                  </label>
                  <input
                    type="tel"
                    value={formData.no_telepon}
                    onChange={(e) => setFormData({ ...formData, no_telepon: e.target.value })}
                    placeholder="081234567890"
                    className={`w-full px-3 py-2 border rounded-lg ${
                      isDarkMode 
                        ? 'bg-gray-700 border-gray-600 text-white' 
                        : 'bg-white border-gray-300 text-gray-800'
                    } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                  />
                </div>
              </div>

              <div>
                <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Status
                </label>
                <select
                  value={formData.is_active}
                  onChange={(e) => setFormData({ ...formData, is_active: parseInt(e.target.value) })}
                  className={`w-full px-3 py-2 border rounded-lg ${
                    isDarkMode 
                      ? 'bg-gray-700 border-gray-600 text-white' 
                      : 'bg-white border-gray-300 text-gray-800'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                >
                  <option value={1}>Aktif</option>
                  <option value={0}>Non-Aktif</option>
                </select>
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={handleCancel}
                className={`flex-1 px-4 py-2 border rounded-lg font-medium ${
                  isDarkMode 
                    ? 'border-gray-600 text-gray-300 hover:bg-gray-700' 
                    : 'border-gray-300 text-gray-700 hover:bg-gray-50'
                } transition`}
              >
                Batal
              </button>
              <button
                onClick={handleSave}
                className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition flex items-center justify-center gap-2"
              >
                <Save size={18} />
                {dosenViewMode === 'edit' ? 'Update' : 'Simpan'}
              </button>
            </div>
          </div>
        </>
      )}

      {/* LIST VIEW */}
      {dosenViewMode === 'list' && (
        <>
          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className={`p-4 rounded-xl ${isDarkMode ? 'bg-gray-800 border border-gray-700' : 'bg-white border border-gray-200'} shadow-sm`}>
              <p className={`text-xs font-semibold ${isDarkMode ? 'text-gray-400' : 'text-gray-600'} mb-1`}>TOTAL DOSEN</p>
              <p className={`text-2xl font-bold ${isDarkMode ? 'text-white' : 'text-gray-800'}`}>
                {dosenList.length}
              </p>
            </div>
            <div className={`p-4 rounded-xl ${isDarkMode ? 'bg-gray-800 border border-gray-700' : 'bg-white border border-gray-200'} shadow-sm`}>
              <p className={`text-xs font-semibold ${isDarkMode ? 'text-gray-400' : 'text-gray-600'} mb-1`}>AKTIF</p>
              <p className={`text-2xl font-bold text-green-600`}>
                {dosenList.filter(d => d.is_active === 1).length}
              </p>
            </div>
            <div className={`p-4 rounded-xl ${isDarkMode ? 'bg-gray-800 border border-gray-700' : 'bg-white border border-gray-200'} shadow-sm`}>
              <p className={`text-xs font-semibold ${isDarkMode ? 'text-gray-400' : 'text-gray-600'} mb-1`}>NON-AKTIF</p>
              <p className={`text-2xl font-bold text-red-600`}>
                {dosenList.filter(d => d.is_active === 0).length}
              </p>
            </div>
          </div>

          {/* Toolbar */}
          <div className={`glass-card ${isDarkMode ? 'bg-gray-800/60 border-gray-700' : 'bg-white/90 border-gray-200'}`}>
            <div className="p-4 flex flex-col md:flex-row gap-3 items-center">
              {/* Search */}
              <div className="flex-1 relative">
                <Search size={16} className={`absolute left-3 top-1/2 transform -translate-y-1/2 ${isDarkMode ? 'text-gray-500' : 'text-gray-400'}`} />
                <input
                  type="text"
                  placeholder="Cari NIP, Nama atau prodi..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className={`w-full pl-9 pr-3 py-2 rounded-lg border text-sm ${
                    isDarkMode 
                      ? 'bg-gray-700/50 border-gray-600 text-white placeholder-gray-400' 
                      : 'bg-white border-gray-300 text-gray-800 placeholder-gray-500'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                />
              </div>

              {/* Filter Prodi */}
              <select
                value={filterProdi}
                onChange={(e) => setFilterProdi(e.target.value)}
                className={`px-3 py-2 rounded-lg border text-sm ${
                  isDarkMode 
                    ? 'bg-gray-700/50 border-gray-600 text-white' 
                    : 'bg-white border-gray-300 text-gray-800'
                } focus:outline-none focus:ring-2 focus:ring-blue-500`}
              >
                <option value="all">Semua Prodi</option>
                {prodiList.map(prodi => (
                  <option key={prodi} value={prodi}>{prodi}</option>
                ))}
              </select>

              {/* Filter Status */}
              <select
                value={filterActive}
                onChange={(e) => setFilterActive(e.target.value)}
                className={`px-3 py-2 rounded-lg border text-sm ${
                  isDarkMode 
                    ? 'bg-gray-700/50 border-gray-600 text-white' 
                    : 'bg-white border-gray-300 text-gray-800'
                } focus:outline-none focus:ring-2 focus:ring-blue-500`}
              >
                <option value="all">Semua Status</option>
                <option value="active">Aktif</option>
                <option value="inactive">Non-Aktif</option>
              </select>

              {/* Filter Periode */}
              <select
                value={filterPeriode}
                onChange={(e) => setFilterPeriode(e.target.value)}
                className={`px-3 py-2 rounded-lg border text-sm ${
                  isDarkMode 
                    ? 'bg-gray-700/50 border-gray-600 text-white' 
                    : 'bg-white border-gray-300 text-gray-800'
                } focus:outline-none focus:ring-2 focus:ring-blue-500`}
              >
                <option value="all">Semua Periode</option>
                {periodeList.slice(0, 3).map(periode => (
                  <option key={periode.id_periode} value={periode.id_periode}>
                    {periode.nama_periode} {periode.is_active ? '✓' : ''}
                  </option>
                ))}
              </select>
          <button
            onClick={() => setShowImportModal(true)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
              isDarkMode 
                ? 'bg-gray-700 hover:bg-gray-600 text-white border border-gray-600' 
                : 'bg-white/90 hover:bg-gray-50 text-gray-700 border border-gray-300'
            }`}
          >
            <Upload size={16} />
            Import
          </button>
          
          {/* Add Button */}
          <button
            onClick={handleAdd}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-all"
          >
            <Plus size={16} />
            TAMBAH DOSEN
          </button>
        </div>
      </div>

      {/* Table */}
      <div className={`glass-card overflow-hidden ${isDarkMode ? 'bg-gray-800/60 border-gray-700' : 'bg-white/90 border-gray-200'}`}>
          {isLoading ? (
            <div className="flex items-center justify-center py-16">
              <div className="w-12 h-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
            </div>
          ) : filteredDosen.length === 0 ? (
            <div className="text-center py-16">
              <GraduationCap size={48} className={`mx-auto mb-3 ${isDarkMode ? 'text-gray-600' : 'text-gray-300'}`} />
              <p className={isDarkMode ? 'text-gray-400' : 'text-gray-500'}>
                {searchQuery ? 'Tidak ada dosen yang cocok dengan pencarian' : 'Belum ada data dosen'}
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className={isDarkMode ? 'bg-gray-900 border-b border-gray-700' : 'bg-gray-50 border-b border-gray-200'}>
                  <tr>
                    <th className={`px-4 py-3 text-left text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>NO</th>
                    <th className={`px-4 py-3 text-left text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>NIP</th>
                    <th className={`px-4 py-3 text-left text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>NAMA</th>
                    <th className={`px-4 py-3 text-left text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>PRODI</th>
                    <th className={`px-4 py-3 text-left text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>KONTAK</th>
                    <th className={`px-4 py-3 text-center text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>STATUS</th>
                    <th className={`px-4 py-3 text-center text-xs font-bold ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>AKSI</th>
                  </tr>
                </thead>
                <tbody>
                  {paginatedDosen.map((dosen, idx) => (
                    <tr 
                      key={dosen.id_dosen}
                      className={`border-b ${
                        isDarkMode 
                          ? 'border-gray-700 hover:bg-gray-700/50' 
                          : 'border-gray-100 hover:bg-gray-50'
                      } transition`}
                    >
                      <td className={`px-4 py-3 text-sm ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                        {startIndex + idx + 1}
                      </td>
                      <td className={`px-4 py-3 text-sm ${isDarkMode ? 'text-gray-300' : 'text-gray-800'} font-mono`}>
                        {dosen.nip}
                      </td>
                      <td className={`px-4 py-3 text-sm ${isDarkMode ? 'text-white' : 'text-gray-800'} font-semibold`}>
                        {dosen.nama}
                      </td>
                      <td className={`px-4 py-3 text-sm ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                        {dosen.prodi || '-'}
                      </td>
                      <td className={`px-4 py-3 text-xs ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                        <div>{dosen.email || '-'}</div>
                        <div className="font-mono">{dosen.no_telepon || '-'}</div>
                      </td>
                      <td className="px-4 py-3 text-center">
                        {dosen.is_active ? (
                          <span className="inline-flex items-center gap-1 px-2 py-1 bg-green-100 text-green-700 rounded-full text-xs font-semibold">
                            <UserCheck size={12} />
                            Aktif
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 px-2 py-1 bg-red-100 text-red-700 rounded-full text-xs font-semibold">
                            <UserX size={12} />
                            Non-Aktif
                          </span>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center justify-center gap-2">
                          <button
                            onClick={() => handleEdit(dosen)}
                            className={`p-1.5 rounded-md transition ${
                              isDarkMode 
                                ? 'text-blue-400 hover:bg-blue-900/30' 
                                : 'text-blue-600 hover:bg-blue-100'
                            }`}
                            title="Edit"
                          >
                            <Edit2 size={16} />
                          </button>
                          <button
                            onClick={() => handleToggleActive(dosen.id_dosen, dosen.is_active, dosen.nama)}
                            className={`p-1.5 rounded-md transition ${
                              isDarkMode 
                                ? 'text-yellow-400 hover:bg-yellow-900/30' 
                                : 'text-yellow-600 hover:bg-yellow-100'
                            }`}
                            title={dosen.is_active ? 'Nonaktifkan' : 'Aktifkan'}
                          >
                            {dosen.is_active ? <UserX size={16} /> : <UserCheck size={16} />}
                          </button>
                          <button
                            onClick={() => handleDelete(dosen.id_dosen, dosen.nama)}
                            className={`p-1.5 rounded-md transition ${
                              isDarkMode 
                                ? 'text-red-400 hover:bg-red-900/30' 
                                : 'text-red-600 hover:bg-red-100'
                            }`}
                            title="Hapus"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Pagination Controls */}
          {filteredDosen.length > 0 && (
            <div className={`flex flex-col md:flex-row items-center justify-between gap-4 p-4 ${isDarkMode ? 'bg-gray-800/40 border-t border-gray-700' : 'bg-gray-50/50 border-t border-gray-200'}`}>
              {/* Items per page selector */}
              <div className="flex items-center gap-3">
                <span className={`text-sm ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Tampilkan:
                </span>
                <select
                  value={itemsPerPage}
                  onChange={(e) => handleItemsPerPageChange(Number(e.target.value))}
                  className={`px-3 py-1.5 rounded-lg border text-sm ${
                    isDarkMode 
                      ? 'bg-gray-700 border-gray-600 text-white' 
                      : 'bg-white border-gray-300 text-gray-800'
                  } focus:outline-none focus:ring-2 focus:ring-blue-500`}
                >
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
                <span className={`text-sm ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                  dari {filteredDosen.length} data
                </span>
              </div>

              {/* Page navigation */}
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handlePageChange(currentPage - 1)}
                  disabled={currentPage === 1}
                  className={`p-2 rounded-lg transition ${
                    currentPage === 1
                      ? 'opacity-50 cursor-not-allowed'
                      : isDarkMode
                        ? 'hover:bg-gray-700 text-gray-300'
                        : 'hover:bg-gray-200 text-gray-700'
                  }`}
                >
                  <ChevronLeft size={18} />
                </button>

                {/* Page numbers */}
                <div className="flex items-center gap-1">
                  {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => {
                    // Show first page, last page, current page, and pages around current
                    if (
                      page === 1 ||
                      page === totalPages ||
                      (page >= currentPage - 1 && page <= currentPage + 1)
                    ) {
                      return (
                        <button
                          key={page}
                          onClick={() => handlePageChange(page)}
                          className={`px-3 py-1.5 rounded-lg text-sm font-medium transition ${
                            page === currentPage
                              ? 'bg-blue-600 text-white'
                              : isDarkMode
                                ? 'hover:bg-gray-700 text-gray-300'
                                : 'hover:bg-gray-200 text-gray-700'
                          }`}
                        >
                          {page}
                        </button>
                      );
                    } else if (
                      page === currentPage - 2 ||
                      page === currentPage + 2
                    ) {
                      return (
                        <span key={page} className={isDarkMode ? 'text-gray-500' : 'text-gray-400'}>
                          ...
                        </span>
                      );
                    }
                    return null;
                  })}
                </div>

                <button
                  onClick={() => handlePageChange(currentPage + 1)}
                  disabled={currentPage === totalPages}
                  className={`p-2 rounded-lg transition ${
                    currentPage === totalPages
                      ? 'opacity-50 cursor-not-allowed'
                      : isDarkMode
                        ? 'hover:bg-gray-700 text-gray-300'
                        : 'hover:bg-gray-200 text-gray-700'
                  }`}
                >
                  <ChevronRight size={18} />
                </button>
              </div>
            </div>
          )}
        </div>
        </>
      )}

      {/* Import Excel Modal */}
      {showImportModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50" onClick={() => !isImporting && setShowImportModal(false)}>
          <div 
            className={`${isDarkMode ? 'bg-gray-800' : 'bg-white'} rounded-xl shadow-2xl p-6 w-full max-w-2xl`}
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center gap-3 mb-5">
              <FileSpreadsheet size={24} className="text-green-600" />
              <h4 className={`text-xl font-bold ${isDarkMode ? 'text-white' : 'text-gray-800'}`}>
                Import Data Dosen dari Excel
              </h4>
            </div>

            {!importResult ? (
              <>
                <div className={`border-2 border-dashed rounded-lg p-8 text-center mb-4 ${
                  isDarkMode ? 'border-gray-600' : 'border-gray-300'
                }`}>
                  <Upload size={48} className={`mx-auto mb-3 ${isDarkMode ? 'text-gray-500' : 'text-gray-400'}`} />
                  <p className={`text-sm mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                    {importFile ? importFile.name : 'Pilih file Excel (.xlsx, .xls, .csv)'}
                  </p>
                  <input
                    type="file"
                    accept=".xlsx,.xls,.csv"
                    onChange={(e) => setImportFile(e.target.files[0])}
                    className="hidden"
                    id="import-file"
                  />
                  <label
                    htmlFor="import-file"
                    className={`inline-block px-4 py-2 rounded-lg cursor-pointer transition ${
                      isDarkMode 
                        ? 'bg-gray-700 text-gray-300 hover:bg-gray-600' 
                        : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                    }`}
                  >
                    Pilih File
                  </label>
                </div>

                <div className={`p-4 rounded-lg mb-4 ${isDarkMode ? 'bg-white-900/20 border border-white-800' : 'bg-white-50 border border-white-200'}`}>
                  <p className={`text-sm text-center font-semibold mb-2 ${isDarkMode ? 'text-blue-300' : 'text-blue-800'}`}>
                    Kolom wajib : 
                  </p>
                  <ul className={`text-xs text-center space-y-1 ${isDarkMode ? 'text-blue-200' : 'text-blue-700'}`}>
                    <li> <strong>NIP, Nama, Prodi, Email, No.Telepon(opsional)</strong>  </li>
                  </ul>
                </div>

                <div className="flex gap-3">
                  <button
                    onClick={() => {
                      setShowImportModal(false);
                      setImportFile(null);
                    }}
                    disabled={isImporting}
                    className={`flex-1 px-4 py-2 border rounded-lg font-medium ${
                      isDarkMode 
                        ? 'border-gray-600 text-gray-300 hover:bg-gray-700' 
                        : 'border-gray-300 text-gray-700 hover:bg-gray-50'
                    } transition disabled:opacity-50`}
                  >
                    Batal
                  </button>
                  <button
                    onClick={handleImportFile}
                    disabled={!importFile || isImporting}
                    className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isImporting ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                        Importing...
                      </>
                    ) : (
                      <>
                        <Upload size={18} />
                        Import
                      </>
                    )}
                  </button>
                </div>
              </>
            ) : (
              <>
                <div className={`p-4 rounded-lg mb-4 ${
                  importResult.success 
                    ? (isDarkMode ? 'bg-green-900/20 border border-green-800' : 'bg-green-50 border border-green-200')
                    : (isDarkMode ? 'bg-red-900/20 border border-red-800' : 'bg-red-50 border border-red-200')
                }`}>
                  <p className={`text-sm font-semibold mb-2 ${
                    importResult.success 
                      ? (isDarkMode ? 'text-green-300' : 'text-green-800')
                      : (isDarkMode ? 'text-red-300' : 'text-red-800')
                  }`}>
                    {importResult.success ? '✅ Import Berhasil!' : '❌ Import Gagal'}
                  </p>
                  <p className={`text-xs ${
                    importResult.success 
                      ? (isDarkMode ? 'text-green-200' : 'text-green-700')
                      : (isDarkMode ? 'text-red-200' : 'text-red-700')
                  }`}>
                    {importResult.message}
                  </p>
                  {importResult.success && (
                    <div className={`mt-2 text-xs ${isDarkMode ? 'text-green-200' : 'text-green-700'}`}>
                      <p>Total diproses: <strong>{importResult.total}</strong></p>
                      <p>Berhasil: <strong>{importResult.success_count}</strong></p>
                      {importResult.failed_count > 0 && (
                        <p>Gagal: <strong>{importResult.failed_count}</strong></p>
                      )}
                    </div>
                  )}
                  {importResult.errors && importResult.errors.length > 0 && (
                    <div className="mt-3">
                      <p className={`text-xs font-semibold mb-1 ${isDarkMode ? 'text-red-300' : 'text-red-800'}`}>
                        Error detail:
                      </p>
                      <ul className={`text-xs space-y-1 max-h-32 overflow-y-auto ${isDarkMode ? 'text-red-200' : 'text-red-700'}`}>
                        {importResult.errors.slice(0, 10).map((err, idx) => (
                          <li key={idx}>• {err}</li>
                        ))}
                        {importResult.errors.length > 10 && (
                          <li>... dan {importResult.errors.length - 10} error lainnya</li>
                        )}
                      </ul>
                    </div>
                  )}
                </div>

                <button
                  onClick={() => {
                    setShowImportModal(false);
                    setImportFile(null);
                    setImportResult(null);
                  }}
                  className="w-full px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition"
                >
                  Tutup
                </button>
              </>
            )}
          </div>
        </div>
      )}
    </section>
  );
}
